_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 77
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 77
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.9
            "6": 4.51.1
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 1
bf16:
    value: true
dataset_size:
    value: 2708
embedding_dim:
    value: 1544
epochs:
    value: 1
freeze_backbone:
    value: true
learning_rate:
    value: 0.002
lm_model:
    value: /fs-computility/mabasic/shared/models/Qwen2.5-7B-Instruct
max_seq_length:
    value: 512
projection_dim:
    value: null
projection_type:
    value: linear
