_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 77
            "2":
                - 1
                - 11
                - 49
                - 55
                - 77
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.9
            "6": 4.51.0
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 16
dataset_size:
    value: 2708
embedding_dim:
    value: 1433
epochs:
    value: 5
freeze_lm:
    value: true
learning_rate:
    value: 5e-05
lm_model:
    value: gpt2
projection_dim:
    value: 512
