wandb_version: 1

input_dim:
  desc: null
  value: 1433
hidden_dim:
  desc: null
  value: 256
K:
  desc: null
  value: 3
M_list:
  desc: null
  value:
  - 256
  - 128
  - 64
p:
  desc: null
  value: 20
num_nodes:
  desc: null
  value: 100
tokenizer_epochs:
  desc: null
  value: 100
tokenizer_lr:
  desc: null
  value: 0.001
stage:
  desc: null
  value: complete
dataset:
  desc: null
  value: cora
batch_size:
  desc: null
  value: 16
train_llm:
  desc: null
  value: true
llm_epochs:
  desc: null
  value: 30
llm_lr:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745850595.284504
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 77
      2:
      - 1
      - 11
      - 49
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.12
      6: 4.31.0
      8:
      - 5
      13: linux-x86_64
dataset_name:
  desc: null
  value: cora
